# Generated by Django 5.2.3 on 2025-10-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
